# Generated by Django 5.0.6 on 2025-06-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_uploader", "0004_geneticdata_encrypted_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="columns",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="data_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
